# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings


exclude: ["README.md"] # files to exclude
highlighter: rouge
disqus: henkraap
baseurl: http://henkraap.github.io

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: The World Through A Lens

description: Photography by Henk Raap
author:
  name: Henk
  email: henkraap@gmail.com
  twitter: turniph
  bio: Photography by Henk Raap
  email_md5: 948e2cd8fd6136e06c4d80d00f5eea68
# Gems
gems:
- jekyll-paginate

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
rss_path: feed.xml
categories_path: categories.html
# tags_path: tags.html

BASE_PATH: http://henkraap.github.io
